### ISSUE TITLE
请支持jdk1.8，构建同时支持build.sbt文件构建

### ISSUE THREAD

**Issue by allon517** [CSUG/HouseMD#112]

**Comment by zhongl** [comment]
如果你是为了使用 HouseMD ， 我推荐你看看https://github.com/oldmanpushcart/greys-anatomy，起初它是 HouseMD 的 Java 版， 关键是现在它一直保持更新。（我现在比较懒）

如果你是为了研究学习，那这个问题不妨你自己动手弄一下， 我会非常乐意看到你的 Pull Request :)
