### ISSUE TITLE
java.lang.VerifyError

### ISSUE THREAD

**Issue by AlexGKing** [CSUG/HouseMD#114]
执行命令：housemd> trace -t 4 HelloWorld.execute
报错信息如下所示：
WARN : Failed to probe class HelloWorld because of java.lang.VerifyError
No traced method invoked

No traced method invoked

No traced method invoked

No traced method invoked

INFO : Ended by timeout
INFO : Reset class HelloWorld

如何解决啊？

**Comment by binnchx** [comment]
同遇到这个问题

**Comment by AlexGKing** [comment]
已经放弃了HouseMD了

**Comment by JarvisZhu** [comment]
我也遇到这个问题了、、、不知道怎么解决

**Comment by zhongl** [comment]
🙏 感谢以上各位还如此青睐HouseMD！

如果各位希望有个好用的诊断工具，那么正如我在README中推荐的， 请使用 @oldmanpushcart 开发的[greys-anatomy](https://github.com/oldmanpushcart/greys-anatomy)。

如果想研究学习实现原理， 还请各位阅读源码。

> 友情提示： 根据楼主的错误信息， 多半原因出在字节码版本不兼容上， 我非常期待有人能够贡献代码来Fix 😊
