### ISSUE TITLE
sbt build error help.

### ISSUE THREAD

**Issue by hi-wayne** [CSUG/HouseMD#90]
error info
E:\houseMD\housemd>sbt proguard
[info] Loading project definition from E:\houseMD\housemd\project
[info] Set current project to housemd (in build file:/E:/houseMD/housemd/)
[info] Compiling 21 Scala sources and 4 Java sources to E:\houseMD\housemd\target\scala-2.9.2\classes...
[error] E:\houseMD\housemd\src\main\scala\com\github\zhongl\housemd\house\House.scala:19: object tools is not a member of package com.sun
[error] import com.sun.tools.attach.VirtualMachine
[error]                ^
[error] one error found
[error] {file:/E:/houseMD/housemd/}housemd/compile:compile: Compilation failed
[error] Total time: 5 s, completed 2012-12-26 13:22:48

**Comment by allon517** [comment]
这个问题我也搞了很久，也是不行

**Comment by zhongl** [comment]
#112
